-- CreateEnum
CREATE TYPE "Category" AS ENUM ('APPETIZER', 'SOUP', 'SALAD', 'MAIN_COURSE', 'SIDE_DISH', 'DESSERT', 'BEVERAGE', 'BREAKFAST', 'BRUNCH', 'LUNCH', 'DINNER', 'SNACK', 'BAKED_GOOD', 'SAUCE', 'CONDIMENT', 'SPECIAL');

-- AlterTable
ALTER TABLE "recipe" ADD COLUMN     "category" "Category" NOT NULL DEFAULT 'MAIN_COURSE';
